# 47장 에러-처리

## try ... catch ... finally

- 프로그램을 강제 종료 시키지 않고 에러처리 가능
- finally, catch 문 생략 가능
  - 하지만 catch문이 없으면 try 문의 의미가 없기 때문에 catch 문은 생략하지 않는다.

1. try 코드블록에 포함된 문 중에서 에러가 발생
1. catch 문의 err 변수에 전달되고 catch 코드 블록이 실행
1. finally 코드 블록이 에러 발생과 상관없이 반드시 한 번 실행

### throw 문

- 생성된 에러 객체를 throw 문으로 던져야 한다.

### 에러 전파

- throw된 에러를 캐치하지 않으면 호출자 방향으로 전파된다.
- throw된 에러를 어디에서도 캐치하지 않으면 프로그램은 강제 종료된다.
