# 46장 제너레이터와 async/await

# 46.1 제너레이터란?

제너레이터란 코드 블록의 실행을 중단 시켰다가 필요할 때 다시 실행 시킬 수 있는 특수한 함수이다. 제너레이터와 일반 함수의 차이는 다음과 같다.

1. 제너레이터 함수는 함수 호출자에게 함수 실행의 제어권을 양도 할 수 있다.

일반 함수는 호츨되면 함수의 코드를 일괄 적으로 실행하여 호출자는 호출 이후 코드 진행에 관여하지 않는다. 하지만 호출자가 호출한 것이 제너레이터 함수라면 호출자가 실행을 제어 할 수 있다.

1. 제너레이터 함수는 함수 호출자와 함수의 상태를 주고 받을 수 있다.

제너레이터 함수는 함수가 진행 중에도 호출자와 양방향으로 상태를 주고 받을 수 있다.

1. 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.

제너레이터는 이터러블이면서 이터레이터인 제레이터 객체를 반환한다.

# 46.2 제너레이터 함수의 정의

제너레이터 함수의 정의 방법은 다음과 같다.

```jsx
function* genfunc() {
  // 함수 선언 시에 *를 붙여주고
  yield 1; // 하나 이상의 yield 표현식을 포함해야 한다.
}
```

\*는 애스터리스크라고 하며 일반적으로 function 키워드 바로 뒤에 붙이지만 function 키워드와 함수 이름 사이라면 어디든 가능하다. 그리고 화살표 함수는 제너레이터 함수로 정의 할 수 없으며 new연산자와 함께 생성자 함수로서 사용 할 수 없다.

# 46.3 제너레이터 객체

제너레이터 함수는 코드 블록을 실행하는 것이 아니라 이터러블 이면서 이터레이터인 제너레이터 객체를 생성한다.

next 메서드를 통해 반환된 이터레이터 리절트 객체는 value 와 done 프로퍼티를 갖는다. value 프로퍼티는 가장 처음 만나는 yield 표현식의 값을 갖는다, 그라고 done 프로퍼티는 코드 실행이 끝나는지 여부에 따라 불린 값을 가진다.

return메서드를 통해 반환된 이터레이터 리절트 객체는 인수로 전달받은 값이 value 값이고 done 프로퍼티는 true이다.

throw 메서드를 통해 호출 하게 되면 인수로 전달받은 에러를 발생시키고 value값은 undefined, done값은 true인 이터레이터 리절트 객체를 반환한다.

# 46.4 제너레이터의 일시 중지와 재개

제너레이터 함수는 yield 키워드 의 표현식 까지만 실행하고 평가식의 평가 결과를 함수 호출자에게 반환한다.

```jsx
function* genFunc() {
  yield 1;
  yield 2;
  yield 3;
}

const gen = genFunc();
console.log(gen.next()); // {value : 1, done : false}
console.log(gen.next()); // {value : 2, done : false}
console.log(gen.next()); // {value : 3, done : false}
console.log(gen.next()); // {value : undefined, done : true}
```

next 메서드를 호출하면 함수의 진행을 yield 키워드 에서 멈추고 done 프로퍼티를 false인 상태로 반환한다. 다시 next 메서드를 호출하면 다음 yield 키워드 까지 진행하고 yield 키워드의 값을 다시 반환하며 함수 진행을 멈춘다. 그러다 반환할 yield 키워드를 만나지 못한다면 value : undefined와 done : true를 반환한다.

# 46.6 async/await

제너레이터보다 간단하여 가독성 좋게 비동기 처리를 할 수 있게 ES8에서 async/await 이 생겼다.

async/await은 프로미스를 기반으로 동작하지만 then,catch,finally 등 후속 처리 메서드 없이 마치 동기 처리처럼 사용 할 수 있다.

### 46.6.1 async 함수

await 키워드는 반드시 async함수 내에서 사용해야 한다. function 키워드에 async 키워드를 통해 정의 하면 함수는 항상 프로미스를 반환한다.

### 46.6.2 await 키워드

await 키워드는 프로미스가 settled 상태가 되면 프로미스가 resolve한 처리 결과를 반환한다.

### 46.6.3 에러 처리

async/awiat에서는 에러처리를 try…catch 문을 통해 한다.

만일 catch문을 통해 에로 초리를 하지 않으면 async 함수가 rejected된 프로미스를 반환한다.
